version: '3'
services:
  sLMS-fe:
    build: .
    container_name: sLMS_fe
    user: '${UID_GID}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
      - .next/cache/images:/usr/src/app/.next/cache/images
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
